### PR TITLE
Remove forecastio dependency & Fire Index value sensor

### LINKED ISSUE #297: Fire index value sensor
I've been monitoring the data and it's been bang on.  It's even picking up that I'm in a small higher risk pocket!

image

One addition that might be useful is a fire risk level sensor, or maybe that value can just be included as an attribute to the fire index sensors.  Most people won't understand how the fire index correlates to the more meaningful risk level.   I suppose this could be covered in the docs as well so one could just create their own template sensor if needed.

image

The OpenUV integration does something similar.

image

I've already done it in a template for myself.

```
template:
  - sensor:
      - name: "Fire Risk Level"
        unique_id: fire_risk_level
        icon: mdi:fire
        state: >
          {% set level = states('sensor.pirateweather_fire_index') | int(-1) %}
          {% if level >= 30 %} Extreme
          {% elif level >= 20 %} Very High
          {% elif level >= 10 %} High
          {% elif level >= 5 %} Moderate
          {% else %} Low
          {% endif %}
        availability: "{{ is_number(states('sensor.pirateweather_fire_index')) }}"
```

This is how I end up displaying it in the HA ui.

image

_Originally posted by @jazzyisj in https://github.com/Pirate-Weather/pirateweather/issues/119#issuecomment-2088343476_

### LINKED ISSUE #324: Migrate away from forecastio python library
### Describe the issue

As mentioned in #321 it's probably time to migrate away from using the old forecastio python library as it hasn't been updated in about 6y and is prone to breaking in new python versions.

I'm not super familiar with HA so am not sure if we can just add in the models.py file into the integration and use that. I took a look at some official integrations and all of them seem to use an external library. Which means we may still need a library if you're planning to submit this as an official integration eventually.

If we still need a library to use then the options are

- Use the pirate-weather-python library linked in that issue
- Fork the forecastio library and use that fork instead (I have a fork here https://github.com/cloneofghosts/python-pirate-weather and am willing to add it to the organisation/invite you as a collaborator if you want)

I know the plan at one point was to re-write the integration using that library but the branch hasn't been updated in about a year so probably isn't the plan anymore.

### Home Assistant version

_No response_

### Integration version

_No response_

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/) before opening this issue.
- [X] I have searched this repository and [API Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have queried the API in my browser to confirm the issue is not with the API.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

### PR DESCRIPTION
**Pull request by cloneofghosts**
Removes the forecastio dependency from the integration and adds a fire index value sensor

- Fix #324 
- Fix #297

### CODE REVIEW

**Comment by cloneofghosts** [comment]
@alexander0042 Just waiting on my comments in #297 to be addressed before this can be merged

**Comment by alexander0042** [comment]
Ok, I think I got it working now! Forgot to copy over the config constants to add it, as well as the logic for the daily sensors and a type error. 

Great linting catches- pulling out the calc is a great idea. What did you mean by the comments though?

**Review by alexander0042 — APPROVED** [review]

**Comment by cloneofghosts** [comment]
@alexander0042 I mean the docstrings under the class/definitions

Where it says `"""Mixin class to handle defining the proper __str__/__unicode__ methods in Python 2 or 3."""` in models.py

**Comment by alexander0042** [comment]
Got ya! Just testing it now, but (with some help from ChatGPT) new version incoming

**Comment by cloneofghosts** [comment]
I see you're having issue with the linter. If you have ruff installed you should just be able to run the lint script and it'll fix any fixable issues for you. I could also add it to the GitHub script to make things slightly easier.

**Comment by cloneofghosts** [comment]
Okay looks like the linter passed but the formatter had issues committing even though it did afterwards. Will merge this to live. Want me to create the release or do you want to?

**Comment by alexander0042** [comment]
Do you mind creating this one? I'm trying to get ruff working on my end, since it's about time I figured it out!

**Comment by cloneofghosts** [comment]
Done. Should just be a case of installing ruff and then running the script in the scripts folder at least that's how I run it in VS Code.

**Pull request merged**
